console.log("hello");
let Facts = [" https://www.investopedia.com/terms/b/bank.asp<br> https://www.imf.org/external/pubs/ft/fandd/2012/03/basics.htm<br> https://www.nerdwallet.com/article/banking/what-is-a-bank<br>https://www.investopedia.com/terms/l/loan.asp<br> https://www.nerdwallet.com/article/loans/personal-loans/what-is-a-loan<br> https://corporatefinanceinstitute.com/resources/knowledge/finance/loan/<br>   https://www.investopedia.com/terms/c/creditcard.asp<br> https://www.experian.com/blogs/ask-experian/what-is-a-credit-card/<br> https://www.cnbc.com/select/what-is-a-credit-card/<br> https://www.thebalance.com/what-is-a-debit-card-2385853<br>   https://www.fool.com/the-ascent/banks/checking-accounts/what-is-debit-card/<br>ramseysolutions.com/banking/the-basics-of-your-debit-card<br>https://www.investor.gov/introduction-investing/investing-basics/investment-products/stocks<br>https://www.nerdwallet.com/article/investing/what-are-stocks-how-they-work<br> https://corporatefinanceinstitute.com/resources/knowledge/finance/what-is-a-stock/<br>https://www.investopedia.com/terms/c/cryptocurrency.asp<br>https://www.nerdwallet.com/article/investing/cryptocurrency<br>https://www.coinbase.com/learn/crypto-basics/what-is-cryptocurrency<br>https://www.theverge.com/22310188/nft-explainer-what-is-blockchain-crypto-art-faq<br>https://www.forbes.com/advisor/investing/cryptocurrency/nft-non-fungible-token/<br>https://www.simplilearn.com/tutorials/blockchain-tutorial/what-is-nft<br>", "https://www.investopedia.com/terms/r/rothira.asp<br>https://www.schwab.com/ira/roth-ira/what-is-a-roth-ira<br>https://investor.vanguard.com/accounts-plans/iras/roth-ira<br>https://www.investopedia.com/mortgage/real-estate-investing-guide/<br>https://www.investopedia.com/investing/simple-ways-invest-real-estate/<br>https://www.forbes.com/advisor/investing/how-to-invest-in-real-estate/<br>https://www.investopedia.com/terms/r/residentialrentalproperty.asp<br>https://pocketsense.com/irs-definition-rental-property-7872308.html<br>https://www.fortunebuilders.com/the-pros-and-cons-of-real-estate-wholesaling/<br>https://under30wealth.com/how-to-wholesale-real-estate-case-study-example/<br>https://www.realestatedisruptors.com/blog/the-difference-between-wholesale-and-flipping/<br>https://www.rocketmortgage.com/learn/brrrr#:~:text=<br>The%20BRRRR%20(Buy%2C%20Rehab%2C,fund%20further%20rental%20<br>property%20investment.<br>https://bungalow.com/articles/breaking-down-the-brrrr-method-for-real-estate-investing<br>https://www.fortunebuilders.com/brrrr-strategy/<br>https://www.breezyscroll.com/auto/how-cars-keep-you-poor-why-buying-a-new-car-is-a-bad-investment/<br>https://www.investopedia.com/investing/the-lowdown-on-penny-stocks/#:~:text=Key%20Takeaways,separate%20you%20from%20your%20money<br>https://www.wsj.com/articles/SB10001424127887324662404578330651775508058#:~:text=They%20usually%20make%20poor%20<br>investments,is%20to%20be%20the%20dealer."];
let index = 0

function set_text(id) {
    if(id == 'next' || id == 'nexttop') index++;
    if(id == 'prev' || id == 'prevtop') index--;
    if(index > Facts.length - 1) index = 0;
    if(index < 0) index = Facts.length - 1;
    document.getElementById('div2').innerHTML = Facts[index];
}